#!/bin/sh -e

# ------------------------------------------------------------------------------
# Script to compile PHP from source.
#
# @author Richard Fussenegger <richard@fussenegger.info>
# @copyright 2015 Richard Fussenegger
# @license http://unlicense.org/ PD
# ------------------------------------------------------------------------------

# Version string of the PHP release that should be compiled and installed.
PHP_VERSION='5'

# PHP-FPM system user.
PHP_FPM_USER='www-data'

# PHP-FPM system group.
PHP_FPM_GROUP='www-data'

# The bison version required to compile PHP.
readonly BISON_MAX_VERSION='3.0'

# Whether to perform an apt-get update or not.
APT_GET_UPDATE=true

# Absolute path to the configuration files.
CONFIGURATION_DIRECTORY='/usr/local/etc/php'

# Absolute path to the directory where source files should be kept.
SOURCE_DIRECTORY='/usr/local/src'

# Additional flags that should be passed to the C compiler.
readonly PHP_CFLAGS='-Ofast -m64 -march=native -pipe'


# ------------------------------------------------------------------------------
#                                                               System variables
# ------------------------------------------------------------------------------


# Used to speed-up compilation time.
readonly CPU_COUNT="$(grep -c ^processor /proc/cpuinfo)"

# Make sure that no questions are asked by the operatin system.
export DEBIAN_FRONTEND='noninteractive'

# Absolute path to the directory of the current script.
readonly __DIRNAME__="$(cd -- "$(dirname -- "${0}")"; pwd)"

# For more information on shell colors and other text formatting see:
# http://stackoverflow.com/a/4332530/1251219
readonly BLACK=$(tput setaf 0)
readonly RED=$(tput setaf 1)
readonly GREEN=$(tput setaf 2)
readonly YELLOW=$(tput setaf 3)
readonly BLUE=$(tput setaf 4)
readonly MAGENTA=$(tput setaf 5)
readonly CYAN=$(tput setaf 6)
readonly WHITE=$(tput setaf 7)
readonly BRIGHT=$(tput dim)
readonly NORMAL=$(tput sgr0)
readonly C_EXE=$(tput bold && tput setaf 2)
readonly C_LINK=$(tput bold && tput setaf 6)
readonly C_DIR=$(tput bold && tput setaf 4)


# ------------------------------------------------------------------------------
#                                                                      Functions
# ------------------------------------------------------------------------------


# Print section message.
#
# ARGS:
#   1 - The section's color.
#   2 - The section's name (should be 4 characters long).
#   3 - The section's message.
section()
{
    printf -- '%s[%s]%s %s\n' "$1" "$2" "${NORMAL}" "$3"
}

# Print fail message.
#
# ARGS:
#   1 - The fail message.
fail()
{
    section "${RED}" 'fail' "$1"
}

# Print info message.
#
# ARGS:
#   1 - The info message.
info()
{
    section "${YELLOW}" 'info' "$1"
}

# Print OK message.
#
# ARGS:
#   1 - The OK message.
ok()
{
    section "${GREEN}" ' ok ' "$1"
}

# Install bison.
install_bison()
{
    # We need an older version of bison to compile PHP: http://askubuntu.com/a/461961
    # Note that the version number is hardcoded here, since the links are fixed and not dynamic.
    info "Installing bison ${GREEN}2.7.1${NORMAL}..."
    wget -- 'http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb'
    wget -- 'http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb'
    dpkg -i 'libbison-dev_2.7.1.dfsg-1_amd64.deb'
    dpkg -i 'bison_2.7.1.dfsg-1_amd64.deb'
    rm --force -- 'libbison-dev_2.7.1.dfsg-1_amd64.deb' 'bison_2.7.1.dfsg-1_amd64.deb'
    apt-mark hold bison
}

# Print usage text.
usage()
{
    cat << EOT
Usage: ${0##*/} [OPTION]...
Compile and install PHP from source.

    -c  Configuration directory, defaults to ${YELLOW}${CONFIGURATION_DIRECTORY}${NORMAL}.
    -g  PHP-FPM group, defaults to ${YELLOW}${PHP_FPM_GROUP}${NORMAL}.
    -h  Display this help and exit.
    -n  No apt-get update.
    -s  Source directory, defaults to ${YELLOW}${SOURCE_DIRECTORY}${NORMAL}.
    -u  PHP-FPM username, defaults to ${YELLOW}${PHP_FPM_USER}${NORMAL}.
    -v  PHP version, defaults to ${YELLOW}${PHP_VERSION}${NORMAL}.

Report bugs to richard@fussenegger.info
GitHub repository: https://githbu.com/Fleshgrinder/php-compile
For complete documentation, see: README.md
EOT
}


# ------------------------------------------------------------------------------
#                                                                          Logic
# ------------------------------------------------------------------------------


info 'Fetching latest PHP version...'
PHP_VERSION=$(wget -qO- "https://php.net/releases/index.php?serialize=1&version=${PHP_VERSION}&max=1" | grep -Eo "\"${PHP_VERSION}\.[0-9]+\.[0-9]+\"" | tr -d '"')

# Check for possibly passed options.
while getopts 'c:g:hns:u:v:' OPT
do
    case "${OPT}" in
        c) CONFIGURATION_DIRECTORY="${OPTARG}" ;;
        g) PHP_FPM_GROUP="${OPTARG}" ;;
        h) usage && exit 0 ;;
        n) APT_GET_UPDATE=false ;;
        s) SOURCE_DIRECTORY="${OPTARG}" ;;
        u) PHP_FPM_USER="${OPTARG}" ;;
        v) PHP_VERSION="${OPTARG}" ;;
    esac

    # We have to remove found options from the input for later evaluations of
    # passed arguments in subscripts that are not interested in these options.
    shift $(( $OPTIND - 1 ))
done

# Remove possibly passed end of options marker.
if [ "${1}" = "--" ]
    then shift $(( $OPTIND - 1 ))
fi

# Make all variables read only.
readonly APT_GET_UPDATE;
readonly CONFIGURATION_DIRECTORY;
readonly PHP_FPM_GROUP;
readonly PHP_FPM_USER;
readonly PHP_VERSION;
readonly SOURCE_DIRECTORY;

if [ ${APT_GET_UPDATE} = true ]
then
    info 'Updating package sources...'
    apt-get --yes -- update 1>/dev/null
fi

info 'Installing dependencies...'
apt-get --yes -- install \
    autoconf             \
    automake             \
    build-essential      \
    libbz2-dev           \
    libcurl4-openssl-dev \
    libgmp-dev           \
    libicu-dev           \
    libjpeg-dev          \
    libmcrypt-dev        \
    libpng12-dev         \
    libpq-dev            \
    libssl-dev           \
    libtidy-dev          \
    libtool              \
    libxml2-dev          \
    re2c                 \
    wget

if type bison
then
    # Get the version from the installed bison binary and remove the dots.
    BISON_VERSION=$(bison --version | grep --only-matching -- '[0-9]\.[0-9]')
    if [ $(printf -- '%s' "${BISON_VERSION}" | tr --delete -- '.') -ge $(printf -- '%s' "${BISON_MAX_VERSION}" | tr --delete -- '.') ]
    then
        fail "Installed bison version exceeds maximum version ${RED}${BISON_MAX_VERSION}${NORMAL}!"
        info 'Purging bison installation ...'
        apt-get --yes -- purge bison
        install_bison
    else
        info "Installed bison version ${GREEN}${BISON_VERSION}${NORMAL} is fine for PHP compilation..."
    fi
else
    install_bison
fi

# The GMP header files are installed in a path PHP will not search at.
if [ ! -e '/usr/include/gmp.h' ]
    then ln --symbolic '/usr/include/x86_64-linux-gnu/gmp.h' '/usr/include/gmp.h'
fi

info "Installing PHP ${GREEN}${PHP_VERSION}${NORMAL}..."

# Make sure we operate from the correct directory.
cd -- "${SOURCE_DIRECTORY}"

readonly PHP_SOURCE="${SOURCE_DIRECTORY}/php"

# Checkout PHP source files.
rm --recursive --force -- "${PHP_SOURCE}"
git clone --branch "PHP-${PHP_VERSION}" --depth 1 --single-branch -- https://github.com/php/php-src.git "${PHP_SOURCE}"

# Make sure all files belong to the root user.
chown --recursive -- root:root "${PHP_SOURCE}"

# Make sure we are in the correct directory for compilation.
cd -- "${PHP_SOURCE}"

# Make sure the configure script is up-to-date (only necessary if building from git).
./buildconf --force

info 'Building php-fpm...'
# Have a look at the following page for available extensions:
# https://php.net/extensions.membership
CFLAGS="${PHP_CFLAGS}" \
CPPFLAGS="${PHP_CFLAGS}" \
LDFLAGS='' \
./configure \
    --disable-cli \
    --disable-cgi \
    --disable-rpath \
    --disable-short-tags \
    --enable-bcmath \
    --enable-exif \
    --enable-fpm \
    --enable-ftp \
    --enable-inline-optimization \
    --enable-intl \
    --enable-libgcc \
    --enable-mbstring \
    --enable-pcntl \
    --enable-re2c-cgoto \
    --enable-zip \
    --sysconfdir="${CONFIGURATION_DIRECTORY}" \
    --with-bz2 \
    --with-config-file-path="${CONFIGURATION_DIRECTORY}" \
    --with-config-file-scan-dir="${CONFIGURATION_DIRECTORY}/fpm-enabled" \
    --with-curl \
    --with-fpm-group="${PHP_FPM_GROUP}" \
    --with-fpm-user="${PHP_FPM_USER}" \
    --with-gd \
    --with-gmp \
    --with-jpeg-dir \
    --with-libdir=/lib/x86_64-linux-gnu \
    --with-mcrypt \
    --with-mongodb \
    --with-mysqli=mysqlnd \
    --with-openssl \
    --with-pdo-mysql=mysqlnd \
    --with-pdo-pgsql \
    --with-pgsql \
    --with-png-dir \
    --with-tidy \
    --with-zlib \
    --with-zlib-dir

make clean
make -j ${CPU_COUNT}
make install

rm --force -- "${CONFIGURATION_DIRECTORY}/php-fpm.conf.default"

info 'Building CLI and PEAR...'
CFLAGS="${PHP_CFLAGS}" \
CPPFLAGS="${PHP_CFLAGS}" \
LDFLAGS='' \
./configure \
    --disable-cgi \
    --disable-rpath \
    --disable-short-tags \
    --enable-bcmath \
    --enable-exif \
    --enable-ftp \
    --enable-inline-optimization \
    --enable-intl \
    --enable-libgcc \
    --enable-mbstring \
    --enable-pcntl \
    --enable-re2c-cgoto \
    --enable-zip \
    --sysconfdir="${CONFIGURATION_DIRECTORY}" \
    --with-bz2 \
    --with-config-file-path="${CONFIGURATION_DIRECTORY}" \
    --with-config-file-scan-dir="${CONFIGURATION_DIRECTORY}/cli-enabled" \
    --with-curl \
    --with-fpm-group="${PHP_FPM_GROUP}" \
    --with-fpm-user="${PHP_FPM_USER}" \
    --with-gd \
    --with-gmp \
    --with-jpeg-dir \
    --with-libdir=/lib/x86_64-linux-gnu \
    --with-mcrypt \
    --with-mongodb \
    --with-mysqli=mysqlnd \
    --with-openssl \
    --with-pdo-mysql=mysqlnd \
    --with-pdo-pgsql \
    --with-pear \
    --with-pgsql \
    --with-png-dir \
    --with-tidy \
    --with-zlib \
    --with-zlib-dir

make clean
make -j ${CPU_COUNT}
make install

cat << EOT

${GREEN}[ ok ]${NORMAL} Installation finished.

CONFIG:     ${C_DIR}${CONFIGURATION_DIRECTORY}${NORMAL}
PHP-FPM:    ${C_EXE}$(command -v php-fpm)${NORMAL}*
PHP-CLI:    ${C_EXE}$(command -v php)${NORMAL}*
PHP-CONFIG: ${C_EXE}$(command -v php-config)${NORMAL}*
PEAR:       ${C_EXE}$(command -v pear)${NORMAL}*
PEARDEV:    ${C_EXE}$(command -v peardev)${NORMAL}*
PECL:       ${C_EXE}$(command -v pecl)${NORMAL}*
PHAR:       ${C_EXE}$(command -v phar)${NORMAL}*
PHPIZE:     ${C_EXE}$(command -v phpize)${NORMAL}*

EOT

exit 0
